[en]
  title = "Dao of Healing"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[zh]
  title = "杨医生新冠义诊"
  languageName = "中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh-cn"
